default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: ENTER_YOUR_USERANME
  password: ENTER_YOUR_PASSWORD

development:
  <<: *default
  database: appointment_booking_system_development

test:
  <<: *default
  database: appointment_booking_system_test

production:
  <<: *default
  database: appointment_booking_system_production
  username: appointment_booking_system
  password: <%= ENV["APPOINTMENT_BOOKING_SYSTEM_DATABASE_PASSWORD"] %>
